backend:
  name: git-gateway
  branch: master
media_folder: 'static/img/'
public_folder: 'img'
collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: 'content/post'
    path: '{{slug}}/index'
    create: true  # Allow users to create new documents in this collection
    fields:  # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", required: false, widget: "boolean", default: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Summary", name: "summary", widget: "markdown"}
      - {label: "Featured", name: "featured", required: false, widget: "boolean", default: false}
      - {label: "Authors", name: "authors", required: false, widget: "list", default: ["fredara"]}
      - {label: "Tags", name: "tags", required: false, widget: "list"}
      - {label: "Categories", name: "categories", required: false, widget: "list"}
      - {label: "Projects", name: "projects", required: false, widget: "list"}
      - label: "Featured Image"
        name: "image"
        widget: object
        fields:
          - label: "Upload an image named `featured.jpg/png`"
            name: "filename"
            widget: "image"
            default: "featured"
            media_library:
              config:
                multiple: false
          - {label: Caption, name: caption, widget: string, required: false}
          - {label: Description for screen readers, name: alt_text, widget: string, required: false}
          - label: "Where's the focal point in the image?"
            name: focal_point 
            widget: select
            required: false
            default: "Smart"
            options: ["Smart", "Center", "TopLeft", "Top", "TopRight", "Left", "Right", "BottomLeft", "Bottom", "BottomRight"]
          - {label: Thumbnail Only?, name: preview_only, widget: boolean, required: false, default: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: projects
    label: Projects
    label_singular: Project
    folder: 'content/project'
    path: '{{slug}}/index'
    create: true  # Allow users to create new documents in this collection
    fields:  # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", required: false, widget: "boolean", default: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Summary", name: "summary", widget: "markdown"}
      - {label: "Tags", name: "tags", required: false, widget: "list"}
      - {label: "Categories", name: "categories", required: false, widget: "list"}
      - label: "Featured Image"
        name: "image"
        widget: object
        fields:
          - label: "Upload an image named `featured.jpg/png`"
            name: "filename"
            widget: "image"
            default: "featured"
            media_library:
              config:
                multiple: false
          - {label: Caption, name: caption, widget: string, required: false}
          - {label: Description for screen readers, name: alt_text, widget: string, required: false}
          - label: "Where's the focal point in the image?"
            name: focal_point 
            widget: select
            required: false
            default: "Smart"
            options: ["Smart", "Center", "TopLeft", "Top", "TopRight", "Left", "Right", "BottomLeft", "Bottom", "BottomRight"]
          - {label: Thumbnail Only?, name: preview_only, widget: boolean, required: false, default: false}
      - {label: "Optional external URL for project (replaces project detail page)", name: "external_link", widget: "string", required: false}
      - {label: "Slides", name: "slides", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "talks"
    label: "Talks"
    label_singular: "Talk"
    folder: 'content/talk'
    path: '{{slug}}/index'
    create: true
    fields:  # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", required: false, widget: "boolean", default: false}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Summary", name: "summary", widget: "markdown"}
      - {label: "Abstract", name: "abstract", widget: "markdown", required: false}
      - {label: "Event Name", name: "event", widget: string}
      - {label: "Event Link (https://)", name: event_url, widget: string}
      - {label: Location, name: location, widget: string}
      - label: Address
        name: address
        widget: object
        fields:
          - {label: Street, name: street, widget: string}
          - {label: City, name: city, widget: string}
          - {label: State, name: region, widget: string}
          - {label: Zip, name: postcode, widget: string}
          - {label: Country, name: country, widget: string}
      - {label: "Tags", name: "tags", required: false, widget: "list"}
      - {label: "Categories", name: "categories", required: false, widget: "list"}
      - label: "Featured Image"
        name: "image"
        widget: object
        fields:
          - label: "Upload an image named `featured.jpg/png`"
            name: "filename"
            widget: "image"
            default: "featured"
            media_library:
              config:
                multiple: false
          - {label: Caption, name: caption, widget: string, required: false}
          - {label: Description for screen readers, name: alt_text, widget: string, required: false}
          - label: "Where's the focal point in the image?"
            name: focal_point 
            widget: select
            required: false
            default: "Smart"
            options: ["Smart", "Center", "TopLeft", "Top", "TopRight", "Left", "Right", "BottomLeft", "Bottom", "BottomRight"]
          - {label: Thumbnail Only?, name: preview_only, widget: boolean, required: false, default: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: publications
    label: Publications
    label_singular: Publication
    folder: 'content/publication'
    path: '{{slug}}/index'
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", required: false, widget: "boolean", default: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Abstract", name: "abstract", widget: "markdown"}
      - {label: "Summary", name: "summary", widget: "markdown", required: false}
      - {label: "Featured", name: "featured", required: false, widget: "boolean", default: false}
      - {label: "Authors", name: "authors", widget: "list", default: ["fredara"]}
      - {label: "Tags", name: "tags", required: false, widget: "list"}
      - {label: "Categories", name: "categories", required: false, widget: "list"}
      - label: "Publication types"
        name: "publication_type"
        required: true
        widget: "select"
        options:
          - { label: "Uncategorized", value: "0" }
          - { label: "Conference paper", value: "1" }
          - { label: "Journal article", value: "2" }
          - { label: "Preprint / Working paper", value: "3" }
          - { label: "Report", value: "4" }
          - { label: "Book", value: "5" }
          - { label: "Book section", value: "6" }
          - { label: "Thesis", value: "7" }
          - { label: "Patent", value: "8" }
      - {label: Publication, name: publication, widget: string}
      - {label: "Abbreviated publication name", name: publication_short, widget: string, required: false}
      - {label: "Projects", name: "projects", required: false, widget: "list"}
      - label: "Featured Image"
        name: "image"
        widget: object
        fields:
          - label: "Upload an image named `featured.jpg/png`"
            name: "filename"
            widget: "image"
            default: "featured"
            media_library:
              config:
                multiple: false
          - {label: Caption, name: caption, widget: string, required: false}
          - {label: Description for screen readers, name: alt_text, widget: string, required: false}
          - label: "Where's the focal point in the image?"
            name: focal_point 
            widget: select
            required: false
            default: "Smart"
            options: ["Smart", "Center", "TopLeft", "Top", "TopRight", "Left", "Right", "BottomLeft", "Bottom", "BottomRight"]
          - {label: Thumbnail Only?, name: preview_only, widget: boolean, required: false, default: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/privacy.md"
        label: "Privacy Policy"
        name: "privacy"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Draft", name: "draft", required: false, widget: "boolean", default: false}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Summary", name: "summary", widget: "markdown"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/terms.md"
        label: "Terms"
        name: "terms"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Draft", name: "draft", required: false, widget: "boolean", default: false}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Summary", name: "summary", widget: "markdown"}
          - {label: "Body", name: "body", widget: "markdown"}
